// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imrlgbohcgjioemfxqat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltcmxnYm9oY2dqaW9lbWZ4cWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNzMxNDksImV4cCI6MjA0OTc0OTE0OX0.4PfIneq-hUN9VRuhxCuWD7UVerQsrV17nKUPqr7rpNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);